### ISSUE TITLE
credit to source repositories

### ISSUE THREAD

**Issue by namitjuneja** [rahulkapoor90/VITacademics-Enhancement-Suite#1]
https://github.com/namitjuneja/multiDownloader

**Comment by rahulkapoor90** [comment]
hmm...yeah i could have but then i had this thing in works for months but couldn't figure out how to allow individual files to be downloaded at once so i just consulted your code and pushed the update to users. 

Giving credit to open-source projects has always been my top priority but i never thought this accounts for that. I apologize for this case.

**Comment by namitjuneja** [comment]
@rahulkapoor90  I don't know you but dude, I can see the copied codes even if you have not committed them.
Open source is about taking someone else's work and improving it or building something interesting over it and not privately forking it and calling it your own effort.
Please don't do this in the future.

**Comment by rahulkapoor90** [comment]
yeah, i know. i forgot to update my previous comment. currently i am creating a credits page in which i will include your repository. i made a rookie mistake and namit i apologize for that.

Still not saying your work is my effort and this won't happen again.
