### ISSUE TITLE
First Downloaded file get named by the course number

### ISSUE THREAD

**Issue by mayankbansal10** [rahulkapoor90/VITacademics-Enhancement-Suite#10]
When we download form the course page the first material that gets downloaded gets named by the corse name instead of the regular format.
![image](https://cloud.githubusercontent.com/assets/11739578/19197202/364cc77e-8cd6-11e6-916a-686c789ba78a.png)
As in this case the first ppt gets named by MGT307_TH

**Comment by rahulkapoor90** [comment]
Fixed! Update on it's way.. let me know if any new bugs arise.
