### ISSUE TITLE
Fix notifications for marks change and new messages

### ISSUE THREAD

**Issue by hvarday** [rahulkapoor90/VITacademics-Enhancement-Suite#12]
Previously written code for marks change and notification has bugs and is currently commented out, requires refactoring and proper documentation.

Bugs -
 * On login erroneous notification about marks change pops up.
 * Generalize the storing of marks in `chrome.storage`, should store marks of all users who've used the extension on a system.

**Comment by rahulkapoor90** [comment]
Also:

Things to do:

Include the assets locally in the addon for firefox and chrome.
Add support for opera.
Make firefox extension stable. \* currently unstable.
Improve the bad code written in chrome extension.

**Comment by hvarday** [comment]
Will add another issue to refactor every script and add documentation.

what assets are you talking about, the icons and images?

How different is opera, firefox extension development compared to chrome extension development?

**Comment by rahulkapoor90** [comment]
yes, icons and images, firefox requires to host images locally and i think it's better to do the same with chrome extension as these might get deleted from imgur or vit.ac.in

**Comment by hvarday** [comment]
True, also they being local would save some time downloading it on client side

**Comment by rahulkapoor90** [comment]
yet they will increase the the extension size from currently 200kb to 1mb maybe more.

**Comment by hvarday** [comment]
If there is size issue, we can upload it on Cloudinary, and so the concern about resources getting deleted will be solved.

**Comment by rahulkapoor90** [comment]
yeah nice idea.

**Comment by hvarday** [comment]
I was thinking about 2 features: 
- block sign-in till page loads ( atleast till captacha is filled )
- automatically log into pronto, without having to explicitly click the browser action button

**Comment by rahulkapoor90** [comment]
Okay, will work on that. Can you create a todo file on main page on this repo with the things that could be added.

**Comment by hvarday** [comment]
Yep

**Comment by rahulkapoor90** [comment]
Done & dusted by @lakshaykapoor7198
