### ISSUE TITLE
Add the view message button for Winter Semester 2016-2017 in student menu

### ISSUE THREAD

**Issue by hvarday** [rahulkapoor90/VITacademics-Enhancement-Suite#14]
The student menu option for Fall semester 2016-2017 does not have sub-option to view messages on a separate page, although the link is fully functional. 

The link is [view message](https://vtop.vit.ac.in/student/class_message_view.asp?sem=WS). This feature can be used for upcoming semesters.

**Comment by rahulkapoor90** [comment]
it's been added by us or by vit?

**Comment by hvarday** [comment]
It is by VIT, you can check Winter Sem option, it still has suboption for view message.

The link has parameter sem, which might have values - 
- FS
- WS
- SS
- IS

**Comment by rahulkapoor90** [comment]
okay will add it later.

**Comment by armudgal** [comment]
Changes need to be made in the VES-API repository right?

**Comment by rahulkapoor90** [comment]
@kira0204 yes.

**Comment by vatz88** [comment]
Saw, it's added now.

**Comment by vatz88** [comment]
And how about we keep the WIN SEM tab expanded? Instead of user to click it every time.

**Comment by rahulkapoor90** [comment]
Yeah it's to make quick menu - quick to access otherwise it would be a full menu

**Comment by vatz88** [comment]
Done, check it out now.
