### ISSUE TITLE
Automatically populate `From date` in the attendance page

### ISSUE THREAD

**Issue by hvarday** [rahulkapoor90/VITacademics-Enhancement-Suite#15]
Earlier the `From date` was set a default value, due to changes on the website there's no default date anymore.

* Populating a default date equal to fixed date, like `01-Jan-0000` (which works perfectly fine )

**Comment by rahulkapoor90** [comment]
Can anyone do this? @hvarday @VaTz88

**Comment by hvarday** [comment]
@uppusaikiran fixed this, right?

**Comment by rahulkapoor90** [comment]
yup.
