### ISSUE TITLE
Material UI 

### ISSUE THREAD

**Issue by rahulkapoor90** [rahulkapoor90/VITacademics-Enhancement-Suite#20]
@VaTz88 material UI looks good but  what about new pages like https://vtop.vit.ac.in/student/forgot_pswd.asp. I think the code looks more hard-coded and it should/could be adaptable to multiple pages or any new change introduced by VIT from a few single files. Any thoughts?

**Comment by vatz88** [comment]
Yes, only the login page is hard coded. Rest of the pages will be modified upon loading. See vtop.vit.ac.in

**Comment by rahulkapoor90** [comment]
Okay, it looks good.
