### ISSUE TITLE
Quick Links Improvement

### ISSUE THREAD

**Issue by abishekaditya** [rahulkapoor90/VITacademics-Enhancement-Suite#23]
It would be a lot more pleasing if 

1. the quick links was responsive. Currently it looks like this when the window size is changed
![quick links](https://cloud.githubusercontent.com/assets/9787009/21389049/9680baa6-c7a5-11e6-88cd-7bbfba4b75a5.PNG)
2. the quick links had your preferred links sit at the top of the normal links, because as cool as it is to use, closing it every time some other links are to be opened is "unquick"
3. It would me even better if people could choose what they want to add to the quick links bar.

Looking forward to hear your response. Cheers

**Comment by vatz88** [comment]
About making it responsive i think all laptops have minimum width such that it won't collapse. Otherwise we can add a horizontal scroll. Can't do much because of fixed width frames.

**Comment by rahulkapoor90** [comment]
@abishekaditya Thanks for creating an issue about this, I appreciate that. 

> It would me even better if people could choose what they want to add to the quick links bar.

@VaTz88 can you work on this, it seems like a good enhancement probably adding the quick links option can be added in "options page".

**Comment by rahulkapoor90** [comment]
@abishekaditya @VaTz88 and I will work on your suggestions. Thanks.
