### ISSUE TITLE
Web Materials

### ISSUE THREAD

**Issue by sachmeetsb** [rahulkapoor90/VITacademics-Enhancement-Suite#27]
Web material should open the link in a new tab instead of downloading the page as a html.

**Comment by rahulkapoor90** [comment]
give me more context. you talking about term end paper download?

**Comment by sachmeetsb** [comment]
No. My DSA Teacher made a link for a google form in the course page, and the only thing i can do is download it as a html. I was thinking that the extension should separate Web Material as a link which should open in a new page.

**Comment by rahulkapoor90** [comment]
That's not possible but I will still try. Thanks for creating an issue.
