### ISSUE TITLE
Feature Request: View Students in class

### ISSUE THREAD

**Issue by abhinav-adtechs** [rahulkapoor90/VITacademics-Enhancement-Suite#30]

**Comment by vatz88** [comment]
Are there any APIs available? Otherwise not possible, we can only extract data from the site and modify it's content. We don't store it anywhere.

**Comment by abhinav-adtechs** [comment]
Currently there are no endpoints or loose ends available, as per my knowledge.

**Comment by vatz88** [comment]
Yea that's the problem.
