### ISSUE TITLE
Features not working for Fall sem 

### ISSUE THREAD

**Issue by mayankbansal10** [rahulkapoor90/VITacademics-Enhancement-Suite#9]
Multi Download and various other features like timetable download not working for Fall Sem 16-17
<img width="804" alt="screen shot 2016-08-06 at 21 31 38" src="https://cloud.githubusercontent.com/assets/11739578/17457721/9e957b76-5c1d-11e6-80a0-b868de8d9bde.png">

**Comment by rahulkapoor90** [comment]
Fixed.
